; Bingo Flashboard – ESP32-S3 + 105-LED WS2811 + WiFi AP
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.6.0
    ESP32Async/ESPAsyncWebServer@^3.6.0
    ESP32Async/AsyncTCP@^3.3.2
    bblanchon/ArduinoJson@^6.21.3
board_build.filesystem = spiffs
